### ISSUE TITLE
Various structural tweaks

### ISSUE THREAD

**Issue by jddeal** [jddeal/python-cmr#13]
After messing around with the code and thinking about it a bit, a few structural things popped into my head that could be bundled together:

1. Default params being set to None probably isn't necessary since we simply turn around and return
2. Using reST formatted docstrings would greatly improve IDE intellisense output, open up the possibility of using [Read the Docs](https://readthedocs.org/), and improve overall documentation
3. Should we lint the tests? I could see an argument for this in either direction
4. Is there a strong argument for the \<param\>_val member variables in the tests?

In regards to item 4, the key names as class members makes sense, but putting a tests known good values up there seems like it will be a bit unsustainable. With a larger test, it will need to test multiple cases using different known good and bad values, and it likely wouldn't be relevant for any other test. In addition, there is something to be said about not having to jump to the top of the file to find out the values being tested in any particular test.

**Comment by misnor** [comment]
1. Agreed
2. Sure
3. Lint the tests, its easier to ease up later than to get more strict.
4. No strong argument, just how i went about it in my first go with the tests

**Comment by jddeal** [comment]
Regarding 3, a lot of the linter errors aren't worth addressing (like docstrings on unit tests). Might be possible to add a .pylintrc file in the directory to disable some of those checks.
