### ISSUE TITLE
Add CMRResult class

### ISSUE THREAD

**Issue by jddeal** [jddeal/python-cmr#39]
Right now we're simply returning the first page of results from a search as a dictionary. Wrapping the output in an object would allow for a few different things:

- `page(<num>)` to get a specific page of results
- `all()` to get all results
- `.hits` to retrieve the total number of hits the API reported
- `.url` to retrieve the URL used

The code would then change to be something like 
```python
from cmr import GranuleQuery

api = GranuleQuery()
result = api.short_name("AST_L1T").point(-100, 42).query()  # returns CMRResult

for granule in result.all():
    print(granule["entry_title"])
```

**Comment by matthewhanson** [comment]
I find it pretty useful to get the results as a list, I'm not sure an additional object would add much here. Can you get the # of total hits without getting all the results? That would just be the len of the list.

query url could be useful, but could just be a separate function, query_url() that returns the string.

**Comment by jddeal** [comment]
I think that's a fair point, an entirely separate class probably isn't necessary. The features here could certainly be accomplished within the Query class and updates from #9.

Regarding the total number of hits, yes, the CMR API returns a `CMR-Hits` header that we can take advantage of in order to know the size of a query without having everything returned in the body.

As an example, if you check out the headers on [this query](https://cmr.earthdata.nasa.gov/search/granules.json?page_num=1&short_name=MOD09GA&version=006&temporal[]=2016-10-25&temporal[]=2016-10-25) you should see these CMR headers in the response
```
CMR-Hits:42170
CMR-Request-Id:75e988ab-8bd3-4051-9498-3500c2da9387
CMR-Took:289
```

**Comment by jddeal** [comment]
Going to close this one. Getting pages was accomplished by #42 and #43. Getting all results and number of hits was covered in #43. And returning the used URL doesn't seem all that useful, but the Query class has a `_build_url()` method that can be used to generate the URL based on the current state of the Query.
