### ISSUE TITLE
Configurable CMR mode

### ISSUE THREAD

**Issue by jddeal** [jddeal/python-cmr#46]
CMR has three instances available, and at the moment python-cmr is hardcoded to the operational instance. We should probably make the mode configurable through an optional constructor parameter that's defaulted to their operational environment.

The instances are listed here under the "CMR System Environments": https://wiki.earthdata.nasa.gov/display/CMR/CMR+Data+Partner+User+Guide

**Comment by misnor** [comment]
Environments from link:

CMR OPS: https://cmr.earthdata.nasa.gov/search/
CMR UAT: https://cmr.uat.earthdata.nasa.gov/search/
CMR SIT: https://cmr.sit.earthdata.nasa.gov/search/
